"""
Pydantic Models for Wearables

Data validation models for wearable devices and health metrics.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class HealthMetrics(BaseModel):
    """Health metrics from wearable devices."""
    heart_rate: Optional[int] = Field(None, ge=30, le=250, description="Heart rate in BPM")
    steps: Optional[int] = Field(None, ge=0, description="Step count")
    sleep_hours: Optional[float] = Field(None, ge=0, le=24, description="Sleep duration in hours")
    calories: Optional[int] = Field(None, ge=0, description="Calories burned")
    oxygen_level: Optional[int] = Field(None, ge=0, le=100, description="Blood oxygen saturation %")
    blood_pressure_systolic: Optional[int] = Field(None, ge=60, le=250, description="Systolic BP")
    blood_pressure_diastolic: Optional[int] = Field(None, ge=40, le=150, description="Diastolic BP")


class WearableDataCreate(BaseModel):
    """Request model for creating wearable data entry."""
    device_id: str = Field(..., description="Unique device identifier")
    metrics: HealthMetrics


class WearableDeviceCreate(BaseModel):
    """Request model for registering a wearable device."""
    name: str = Field(..., min_length=1, max_length=100)
    type: str = Field(..., description="Device type (e.g., 'fitness_tracker', 'smart_watch')")
    device_id: str = Field(..., description="External device ID")


class WearableDeviceResponse(BaseModel):
    """Response model for wearable device."""
    id: str
    patient_id: str
    name: str
    type: str
    device_id: str
    is_connected: bool
    battery_level: int
    last_sync_time: Optional[datetime]
    data_points_synced: int
    created_at: datetime
    
    class Config:
        from_attributes = True


class AppleHealthMetric(BaseModel):
    """Single health metric from Apple Health export."""
    type: str = Field(..., description="HealthKit type identifier")
    value: float = Field(..., description="Metric value")
    unit: str = Field(..., description="Unit of measurement")
    startDate: str = Field(..., description="ISO timestamp when measurement started")
    endDate: str = Field(..., description="ISO timestamp when measurement ended")
    sourceApp: Optional[str] = Field(None, description="Source app identifier")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional metadata")


class AppleHealthDataRange(BaseModel):
    """Date range for Apple Health export."""
    startDate: str = Field(..., description="Start date of data range")
    endDate: str = Field(..., description="End date of data range")


class AppleHealthExport(BaseModel):
    """
    Complete Apple Health export structure.
    
    This matches the format exported from iPhone/Apple Watch.
    """
    deviceId: str = Field(..., description="Apple device unique identifier")
    userId: Optional[str] = Field(None, description="User identifier (if available)")
    exportTimestamp: str = Field(..., description="When data was exported")
    dataRange: Optional[AppleHealthDataRange] = Field(None, description="Date range of data")
    metrics: List[AppleHealthMetric] = Field(..., description="List of health metrics")
    
    class Config:
        json_schema_extra = {
            "example": {
                "deviceId": "5233E7EE-EF98-4AEB-9E01-1A81FAB21C43",
                "userId": "CB99F596-9067-4786-AD08-639BBF0A96C0",
                "exportTimestamp": "2025-11-13T06:49:53Z",
                "dataRange": {
                    "startDate": "2025-11-12T06:49:53Z",
                    "endDate": "2025-11-13T06:49:53Z"
                },
                "metrics": [
                    {
                        "type": "HKQuantityTypeIdentifierHeartRate",
                        "value": 79,
                        "unit": "bpm",
                        "startDate": "2025-11-12T06:52:56Z",
                        "endDate": "2025-11-12T06:52:56Z",
                        "sourceApp": "com.apple.health",
                        "metadata": {"device": "Apple Watch"}
                    }
                ]
            }
        }


class DevicePairingRequest(BaseModel):
    """
    Request to pair an iOS device with an Android user account.
    
    Scanned from QR code generated by iOS app.
    """
    userId: str = Field(..., description="iOS user ID from CloudSync app")
    deviceId: str = Field(..., description="iOS device ID (Apple device identifier)")
    deviceName: str = Field(..., description="Device name (e.g., 'John's iPhone')")
    deviceType: str = Field(..., description="Device type (e.g., 'apple_health_iphone')")
    generatedAt: str = Field(..., description="ISO timestamp when QR was generated")
    expiresAt: str = Field(..., description="ISO timestamp when pairing expires")
    pairingCode: str = Field(..., description="Human-readable pairing code (e.g., 'ABCD-1234')")
    androidUserId: str = Field(..., description="Android user ID to link this device to")
    
    class Config:
        json_schema_extra = {
            "example": {
                "userId": "3228128A-7110-4D47-8EDB-3A9160E3808A",
                "deviceId": "207791ED-2518-485D-B4D8-55A23525A485",
                "deviceName": "Priyodip's iPhone",
                "deviceType": "apple_health_iphone",
                "generatedAt": "2025-11-16T10:30:00.000Z",
                "expiresAt": "2025-11-16T10:45:00.000Z",
                "pairingCode": "ABCD-1234",
                "androidUserId": "550e8400-e29b-41d4-a716-446655440000"
            }
        }


class DevicePairingResponse(BaseModel):
    """Response after successful device pairing."""
    message: str
    pairing_id: str
    ios_user_id: str
    ios_device_id: str
    android_user_id: str
    paired_at: datetime
    device_name: str


class PairedDeviceInfo(BaseModel):
    """Information about a paired iOS device."""
    pairing_id: str
    ios_user_id: str
    ios_device_id: str
    device_name: str
    device_type: str
    paired_at: datetime
    is_active: bool
    last_sync: Optional[datetime] = None
    total_metrics_synced: int = 0

